laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('max', ['as' => 'perfil', 'uses' => 'PerfilController@index']);

Route::get('decor/{slug?}', ['as' => 'decor', 'uses' => 'DecorController@index']);
Route::get('cenografia/{slug?}', ['as' => 'cenografia', 'uses' => 'CenografiaController@index']);
Route::get('produtos/{slug?}', ['as' => 'produtos', 'uses' => 'ProdutosController@index']);

Route::get('clipping', ['as' => 'imprensa', 'uses' => 'ImprensaController@index']);

Route::get('blog/c/{categoria}', ['as' => 'blog.cat', 'uses' => 'BlogController@filtroCategoria']);
Route::get('blog/d/{ano}/{mes?}', ['as' => 'blog.data', 'uses' => 'BlogController@filtroData']);
Route::get('blog/{slug?}', ['as' => 'blog', 'uses' => 'BlogController@index']);
Route::post('blog/comentario', ['as' => 'blog.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('perfil', 'Painel\PerfilController');

    Route::resource('decor', 'Painel\DecorController');
    Route::resource('decor.imagens', 'Painel\DecorImagensController');

    Route::resource('cenografia', 'Painel\CenografiaController');
    Route::resource('cenografia.imagens', 'Painel\CenografiaImagensController');

    Route::resource('produtos', 'Painel\ProdutosController');
    Route::resource('produtos.imagens', 'Painel\ProdutosImagensController');

    Route::resource('imprensa', 'Painel\ImprensaController');
    Route::resource('imprensa.imagens', 'Painel\ImprensaImagensController');

    Route::resource('blog/categorias', 'Painel\BlogCategoriasController');
    Route::resource('blog', 'Painel\BlogController');
    Route::post('blog/{post}/comentarios/{id}/aprovacao/{valor}', [
        'as'   => 'painel.blog.comentarios.aprovacao',
        'uses' => 'Painel\BlogComentariosController@aprovacao'
    ]);
    Route::resource('blog.comentarios', 'Painel\BlogComentariosController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato/creditos', 'Painel\CreditosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/models/Decor.php
<?php

class Decor extends Eloquent
{

    protected $table = 'decor';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function imagens()
    {
        return $this->hasMany('DecorImagem', 'decor_id')->orderBy('ordem', 'ASC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

}

laravel/app/controllers/DecorController.php
<?php

class DecorController extends BaseController {

    public function index($slug = null)
    {
        View::share('categoria', 'decor');
        View::share('projetos', Decor::ordenados()->get());

        if (!$slug) {

            return $this->view('frontend.projetos.index');

        } else {

            $selecionado = Decor::with('imagens')->slug($slug)->first();
            if (!$selecionado) App::abort('404');

            View::share('custom_layout', 'projeto');
            View::share('selecionado', $selecionado);
            return $this->view('frontend.projetos.show');

        }
    }

}

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/BlogCategoriasController.php
<?php

namespace Painel;

use \BlogCategoria, \Input, \Validator, \Redirect, \Session, \Str;

class BlogCategoriasController extends BasePainelController {

    private $validation_rules = [
        'titulo' => 'required',
    ];

    public function index()
    {
        $categorias = BlogCategoria::ordenados()->get();

        return $this->view('painel.blog.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return $this->view('painel.blog.categorias.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            BlogCategoria::create($input);
            Session::flash('sucesso', 'Categoria adicionada com sucesso.');

            return Redirect::route('painel.blog.categorias.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao adicionar categoria. Verifique se já existe outra categoria com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $categoria = BlogCategoria::findOrFail($id);

        return $this->view('painel.blog.categorias.edit', compact('categoria'));
    }

    public function update($id)
    {
        $categoria = BlogCategoria::findOrFail($id);
        $input     = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $categoria->update($input);
            Session::flash('sucesso', 'Categoria alterada com sucesso.');

            return Redirect::route('painel.blog.categorias.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar categoria. Verifique se já existe outra categoria com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            BlogCategoria::destroy($id);
            Session::flash('sucesso', 'Categoria removida com sucesso.');

            return Redirect::route('painel.blog.categorias.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover categoria.']);

        }
    }

}

laravel/app/controllers/painel/BlogComentariosController.php
<?php

namespace Painel;

use \Blog, \BlogComentario, \Input, \Session, \Redirect, \Validator, \CropImage;

class BlogComentariosController extends BasePainelController {

    public function index($post_id)
    {
        $post = Blog::find($post_id);
        if(!$post) return Redirect::route('painel.blog.index');

        $comentarios = BlogComentario::post($post_id)->ordenados()->get();

        return $this->view('painel.blog.comentarios.index', compact('post', 'comentarios'));
    }

    public function destroy($blog_id, $comentario_id)
    {
        try {

            BlogComentario::destroy($comentario_id);
            Session::flash('sucesso', 'Comentário removido com sucesso.');

            return Redirect::route('painel.blog.comentarios.index', $blog_id);

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover comentário.']);

        }
    }

    public function aprovacao($post_id, $comentario_id, $valor)
    {
        try {

            $comentario = BlogComentario::find($comentario_id);
            $comentario->aprovado = $valor;
            $comentario->save();
            Session::flash('sucesso', 'Comentário alterado com sucesso.');

            return Redirect::back();

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao alterar comentário.']);

        }
    }

}

laravel/app/controllers/painel/BlogController.php
<?php

namespace Painel;

use \Blog, \BlogCategoria, \Input, \Validator, \Redirect, \Session, \Str, \CropImage;

class BlogController extends BasePainelController {

    private $validation_rules = [
        'blog_categoria_id' => 'required',
        'data'   => 'required',
        'titulo' => 'required',
        'texto'  => 'required',
        'capa'   => 'required|image',
    ];

    private $image_config = [
        'width'  => 400,
        'height' => null,
        'path'   => 'assets/img/blog/capa/'
    ];

    public function index()
    {
        $categorias = BlogCategoria::lists('titulo', 'id');

        if (Input::has('filtro') && BlogCategoria::find(Input::get('filtro'))) {
            $filtro = Input::get('filtro');
            $blog   = Blog::with('comentarios')->ordenados()->categoria($filtro)->paginate(20);
        } else {
            $filtro = null;
            $blog   = Blog::with('comentarios')->ordenados()->paginate(20);
        }

        return $this->view('painel.blog.index', compact('blog', 'categorias', 'filtro'));
    }

    public function create()
    {
        $categorias = BlogCategoria::lists('titulo', 'id');

        return $this->view('painel.blog.create', compact('categorias'));
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['capa'] = CropImage::make('capa', $this->image_config);

            Blog::create($input);
            Session::flash('sucesso', 'Post adicionado com sucesso.');

            return Redirect::route('painel.blog.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar post. Verifique se já existe outro post com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $post = Blog::findOrFail($id);
        $categorias = BlogCategoria::lists('titulo', 'id');

        return $this->view('painel.blog.edit', compact('post', 'categorias'));
    }

    public function update($id)
    {
        $post  = Blog::findOrFail($id);
        $input = Input::all();

        $this->validation_rules['capa'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            $input['publicar'] = (Input::has('publicar') ? 1 : 0);

            $post->update($input);
            Session::flash('sucesso', 'Post alterado com sucesso.');

            return Redirect::route('painel.blog.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar post. Verifique se já existe outro post com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Blog::destroy($id);
            Session::flash('sucesso', 'Post removido com sucesso.');

            return Redirect::route('painel.blog.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover post.']);

        }
    }

}

laravel/app/controllers/painel/CenografiaController.php
<?php

namespace Painel;

use \Cenografia, \Input, \Session, \Redirect, \Validator, \Str, \CropImage;

class CenografiaController extends BasePainelController {

    private $validation_rules = [
        'titulo' => 'required',
        'capa'   => 'required|image'
    ];

    private $image_config = [
        'width'  => 300,
        'height' => 300,
        'path'   => 'assets/img/cenografia/capa/'
    ];

    public function index()
    {
        $cenografia = Cenografia::ordenados()->get();

        return $this->view('painel.cenografia.index', compact('cenografia'));
    }

    public function create()
    {
        return $this->view('painel.cenografia.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['capa'] = CropImage::make('capa', $this->image_config);
            Cenografia::create($input);
            Session::flash('sucesso', 'Projeto criado com sucesso.');

            return Redirect::route('painel.cenografia.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar projeto. Verifique se já existe outro projeto com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $cenografia = Cenografia::findOrFail($id);

        return $this->view('painel.cenografia.edit', compact('cenografia'));
    }

    public function update($id)
    {
        $cenografia = Cenografia::findOrFail($id);
        $input   = Input::all();

        $this->validation_rules['capa'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            $cenografia->update($input);
            Session::flash('sucesso', 'Projeto alterado com sucesso.');

            return Redirect::route('painel.cenografia.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar projeto. Verifique se já existe outro projeto com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Cenografia::destroy($id);
            Session::flash('sucesso', 'Projeto removido com sucesso.');

            return Redirect::route('painel.cenografia.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover projeto.']);

        }
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email'    => 'required|email',
        'telefone' => 'required',
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/views/painel/decor/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="form-group">
    {{ Form::label('titulo', 'Título') }}
    {{ Form::text('titulo', null, ['class' => 'form-control']) }}
</div>

<div class="well form-group">
    {{ Form::label('capa', 'Imagem de capa') }}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/decor/capa/'.$decor->capa) }}" style="display:block; margin-bottom: 10px; max-width:300px;height:auto;">
@endif
    {{ Form::file('capa', ['class' => 'form-control']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.decor.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/decor/create.blade.php
@section('content')

    <legend>
        <h2><small>Decor /</small> Adicionar Projeto</h2>
    </legend>

    {{ Form::open(['route' => 'painel.decor.store', 'files' => true]) }}

        @include('painel.decor._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/decor/edit.blade.php
@section('content')

    <legend>
        <h2><small>Decor /</small> Editar Projeto</h2>
    </legend>

    {{ Form::model($decor, [
        'route' => ['painel.decor.update', $decor->id],
        'method' => 'patch', 'files' => true])
    }}

        @include('painel.decor._form', ['submitText' => 'Alterar'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/decor/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <legend>
        <h2>
            Decor
            <a href="{{ route('painel.decor.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Projeto</a>
        </h2>
    </legend>

    @if(count($decor))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="decor">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Capa</th>
                <th>Título</th>
                <th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($decor as $decor_projeto)

            <tr class="tr-row" id="id_{{ $decor_projeto->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td><img src="{{ url('assets/img/decor/capa/'.$decor_projeto->capa) }}" alt="" style="width:100%;max-width:150px;height:auto;"></td>
                <td>{{ $decor_projeto->titulo }}</td>
                <td><a href="{{ route('painel.decor.imagens.index', $decor_projeto->id) }}" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.decor.destroy', $decor_projeto->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.decor.edit', $decor_projeto->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhum projeto cadastrado.</div>
    @endif

@stop