laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('max', ['as' => 'perfil', 'uses' => 'PerfilController@index']);

Route::get('decor/{slug?}', ['as' => 'decor', 'uses' => 'DecorController@index']);
Route::get('cenografia/{slug?}', ['as' => 'cenografia', 'uses' => 'CenografiaController@index']);
Route::get('produtos/{slug?}', ['as' => 'produtos', 'uses' => 'ProdutosController@index']);

Route::get('clipping', ['as' => 'imprensa', 'uses' => 'ImprensaController@index']);

Route::get('blog/c/{categoria}', ['as' => 'blog.cat', 'uses' => 'BlogController@filtroCategoria']);
Route::get('blog/d/{ano}/{mes?}', ['as' => 'blog.data', 'uses' => 'BlogController@filtroData']);
Route::get('blog/{slug?}', ['as' => 'blog', 'uses' => 'BlogController@index']);
Route::post('blog/comentario', ['as' => 'blog.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('perfil', 'Painel\PerfilController');

    Route::resource('decor', 'Painel\DecorController');
    Route::resource('decor.imagens', 'Painel\DecorImagensController');

    Route::resource('cenografia', 'Painel\CenografiaController');
    Route::resource('cenografia.imagens', 'Painel\CenografiaImagensController');

    Route::resource('produtos', 'Painel\ProdutosController');
    Route::resource('produtos.imagens', 'Painel\ProdutosImagensController');

    Route::resource('imprensa', 'Painel\ImprensaController');
    Route::resource('imprensa.imagens', 'Painel\ImprensaImagensController');

    Route::resource('blog/categorias', 'Painel\BlogCategoriasController');
    Route::resource('blog', 'Painel\BlogController');
    Route::post('blog/{post}/comentarios/{id}/aprovacao/{valor}', [
        'as'   => 'painel.blog.comentarios.aprovacao',
        'uses' => 'Painel\BlogComentariosController@aprovacao'
    ]);
    Route::resource('blog.comentarios', 'Painel\BlogComentariosController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato/creditos', 'Painel\CreditosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/models/Blog.php
<?php

class Blog extends Eloquent
{

    protected $table = 'blog';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('data', 'DESC')->orderBy('id', 'DESC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

    public function scopeCategoria($query, $categoria_id)
    {
        return $query->where('blog_categoria_id', $categoria_id);
    }

    public function categoria()
    {
        return $this->belongsTo('BlogCategoria', 'blog_categoria_id');
    }

    public function scopePublicados($query)
    {
        return $query->where('publicar', 1);
    }

    public function comentarios()
    {
        return $this->hasMany('BlogComentario', 'blog_id')->orderBy('data', 'DESC');
    }

    public function comentariosAprovados()
    {
        return $this->hasMany('BlogComentario', 'blog_id')->orderBy('data', 'DESC')->where('aprovado', 1);
    }

    public function setDataAttribute($date)
    {
        $this->attributes['data'] = Carbon\Carbon::createFromFormat('d/m/Y', $date)->format('Y-m-d');
    }

    public function getDataAttribute($date)
    {
        return Carbon\Carbon::createFromFormat('Y-m-d', $date)->format('d/m/Y');
    }

}

laravel/app/controllers/BlogController.php
<?php

class BlogController extends BaseController {

    public function __construct()
    {
        View::share('custom_layout', 'blog');

        $categorias = BlogCategoria::whereHas('posts', function($query) {
            $query->publicados();
        })->get();
        View::share('categorias', $categorias);
        View::share('categoria_id', null);

        $datas = Blog::publicados()
                       ->select(\DB::raw('YEAR(data) as ano, MONTH(data) as mes'))
                       ->groupBy('ano', 'mes')
                       ->orderBy('ano', 'DESC')
                       ->orderBy('mes', 'DESC')
                       ->get();
        View::share('datas', $datas);
        View::share('ano_selecionado', null);
        View::share('mes_selecionado', null);
    }

    public function index($slug = null)
    {
        if (!$slug) {

            $posts = Blog::with('comentariosAprovados')->ordenados()->publicados()->paginate(15);

            return $this->view('frontend.blog.index', compact('posts'));

        } else {

            $post = Blog::with('comentariosAprovados')->slug($slug)->first();
            if (!$post) return $this->view('frontend.blog.index', ['posts' => null]);

            $data_post = Carbon\Carbon::createFromFormat('d/m/Y', $post->data)->format('Y-m-d');
            $anterior = Blog::select('slug')
                              ->publicados()
                              ->where('data', '<', $data_post)
                              ->orWhere(function($query) use ($data_post, $post) {
                                  $query->where('data', $data_post)
                                        ->where('id', '<', $post->id);
                              })
                              ->orderBy('data', 'DESC')
                              ->orderBy('id', 'DESC')
                              ->first();
            $proximo  = Blog::select('slug')
                              ->publicados()
                              ->where('data', '>', $data_post)
                              ->orWhere(function($query) use ($data_post, $post) {
                                  $query->where('data', $data_post)
                                        ->where('id', '>', $post->id);
                              })
                              ->orderBy('data', 'ASC')
                              ->orderBy('id', 'ASC')
                              ->first();

            return $this->view('frontend.blog.show', compact('post', 'anterior', 'proximo'));
        }
    }

    public function filtroCategoria($slug = null)
    {
        $categoria = BlogCategoria::slug($slug)->first();
        if (!$categoria) return $this->view('frontend.blog.index', ['posts' => null]);

        $posts = Blog::with('comentariosAprovados')->categoria($categoria->id)->ordenados()->publicados()->paginate(15);

        View::share('categoria_id', $categoria->id);
        return $this->view('frontend.blog.index', compact('posts'));
    }

    public function filtroData($ano = null, $mes = null)
    {
        if (!$ano) return $this->view('frontend.blog.index', ['posts' => null]);

        if (!$mes) {
            $posts = Blog::with('comentariosAprovados')->ordenados()->publicados()
                           ->whereRaw("YEAR(data) = $ano")
                           ->paginate(15);
        } else {
            $posts = Blog::with('comentariosAprovados')->ordenados()->publicados()
                           ->whereRaw("YEAR(data) = $ano AND MONTH(data) = $mes")
                           ->paginate(15);
        }

        View::share('ano_selecionado', $ano);
        View::share('mes_selecionado', $mes);
        return $this->view('frontend.blog.index', compact('posts'));
    }

    public function comentario()
    {
        $autor = Input::get('autor');
        $email = Input::get('email');
        $comentario = Input::get('comentario');
        $blog_id = Input::get('blog_id');

        $validation = Validator::make(
            array(
                'autor'      => $autor,
                'email'      => $email,
                'comentario' => $comentario
            ),
            array(
                'autor'      => 'required',
                'email'      => 'required|email',
                'comentario' => 'required'
            )
        );

        if ($validation->fails())
        {
            Debugbar::info($validation->messages());
            $response = array(
                'status'  => 'fail',
                'message' => 'Preencha todos os campos corretamente.'
            );
            return Response::json($response);
        }

        try {

            $object = new BlogComentario;
            $object->blog_id = $blog_id;
            $object->data = Carbon\Carbon::now()->format('d/m/Y');
            $object->autor = $autor;
            $object->email = $email;
            $object->comentario = $comentario;
            $object->save();

            $response = array(
                'status'  => 'success',
                'message' => 'Comentário enviado com sucesso! Aguardando aprovação.'
            );
            return Response::json($response);

        } catch (\Exception $e) {
            Debugbar::info($e);
            $response = array(
                'status'  => 'fail',
                'message' => 'Ocorreu um erro. Tente novamente mais tarde.'
            );
            return Response::json($response);

        }
    }

}

laravel/app/controllers/painel/BlogController.php
<?php

namespace Painel;

use \Blog, \BlogCategoria, \Input, \Validator, \Redirect, \Session, \Str, \CropImage;

class BlogController extends BasePainelController {

    private $validation_rules = [
        'blog_categoria_id' => 'required',
        'data'   => 'required',
        'titulo' => 'required',
        'texto'  => 'required',
        'capa'   => 'required|image',
    ];

    private $image_config = [
        'width'  => 400,
        'height' => null,
        'path'   => 'assets/img/blog/capa/'
    ];

    public function index()
    {
        $categorias = BlogCategoria::lists('titulo', 'id');

        if (Input::has('filtro') && BlogCategoria::find(Input::get('filtro'))) {
            $filtro = Input::get('filtro');
            $blog   = Blog::with('comentarios')->ordenados()->categoria($filtro)->paginate(20);
        } else {
            $filtro = null;
            $blog   = Blog::with('comentarios')->ordenados()->paginate(20);
        }

        return $this->view('painel.blog.index', compact('blog', 'categorias', 'filtro'));
    }

    public function create()
    {
        $categorias = BlogCategoria::lists('titulo', 'id');

        return $this->view('painel.blog.create', compact('categorias'));
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['capa'] = CropImage::make('capa', $this->image_config);

            Blog::create($input);
            Session::flash('sucesso', 'Post adicionado com sucesso.');

            return Redirect::route('painel.blog.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar post. Verifique se já existe outro post com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $post = Blog::findOrFail($id);
        $categorias = BlogCategoria::lists('titulo', 'id');

        return $this->view('painel.blog.edit', compact('post', 'categorias'));
    }

    public function update($id)
    {
        $post  = Blog::findOrFail($id);
        $input = Input::all();

        $this->validation_rules['capa'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            $input['publicar'] = (Input::has('publicar') ? 1 : 0);

            $post->update($input);
            Session::flash('sucesso', 'Post alterado com sucesso.');

            return Redirect::route('painel.blog.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar post. Verifique se já existe outro post com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Blog::destroy($id);
            Session::flash('sucesso', 'Post removido com sucesso.');

            return Redirect::route('painel.blog.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover post.']);

        }
    }

}

laravel/app/views/painel/blog/categorias/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="form-group">
    {{ Form::label('titulo', 'Título') }}
    {{ Form::text('titulo', null, ['class' => 'form-control']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.blog.categorias.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/blog/categorias/create.blade.php
@section('content')

    <legend>
        <h2><small>Blog /</small> Adicionar Categoria</h2>
    </legend>

    {{ Form::open(['route' => 'painel.blog.categorias.store']) }}

        @include('painel.blog.categorias._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/blog/categorias/edit.blade.php
@section('content')

    <legend>
        <h2><small>Blog /</small> Editar Categoria</h2>
    </legend>

    {{ Form::model($categoria, [
        'route' => ['painel.blog.categorias.update', $categoria->id],
        'method' => 'patch', 'files' => true])
    }}

        @include('painel.blog.categorias._form', ['submitText' => 'Alterar'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/blog/categorias/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <a href="{{ route('painel.blog.index') }}" title="Voltar para Blog" class="btn btn-default">&larr; Voltar para Blog</a>

    <legend>
        <h2>
            <small>Blog /</small> Categorias
            <a href="{{ route('painel.blog.categorias.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Categoria</a>
        </h2>
    </legend>

    @if(count($categorias))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="blog_categorias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($categorias as $categoria)

            <tr class="tr-row" id="id_{{ $categoria->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $categoria->titulo }}</td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.blog.categorias.destroy', $categoria->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.blog.categorias.edit', $categoria->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma categoria cadastrada.</div>
    @endif

@stop