laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('max', ['as' => 'perfil', 'uses' => 'PerfilController@index']);

Route::get('decor/{slug?}', ['as' => 'decor', 'uses' => 'DecorController@index']);
Route::get('cenografia/{slug?}', ['as' => 'cenografia', 'uses' => 'CenografiaController@index']);
Route::get('produtos/{slug?}', ['as' => 'produtos', 'uses' => 'ProdutosController@index']);

Route::get('clipping', ['as' => 'imprensa', 'uses' => 'ImprensaController@index']);

Route::get('blog/c/{categoria}', ['as' => 'blog.cat', 'uses' => 'BlogController@filtroCategoria']);
Route::get('blog/d/{ano}/{mes?}', ['as' => 'blog.data', 'uses' => 'BlogController@filtroData']);
Route::get('blog/{slug?}', ['as' => 'blog', 'uses' => 'BlogController@index']);
Route::post('blog/comentario', ['as' => 'blog.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('perfil', 'Painel\PerfilController');

    Route::resource('decor', 'Painel\DecorController');
    Route::resource('decor.imagens', 'Painel\DecorImagensController');

    Route::resource('cenografia', 'Painel\CenografiaController');
    Route::resource('cenografia.imagens', 'Painel\CenografiaImagensController');

    Route::resource('produtos', 'Painel\ProdutosController');
    Route::resource('produtos.imagens', 'Painel\ProdutosImagensController');

    Route::resource('imprensa', 'Painel\ImprensaController');
    Route::resource('imprensa.imagens', 'Painel\ImprensaImagensController');

    Route::resource('blog/categorias', 'Painel\BlogCategoriasController');
    Route::resource('blog', 'Painel\BlogController');
    Route::post('blog/{post}/comentarios/{id}/aprovacao/{valor}', [
        'as'   => 'painel.blog.comentarios.aprovacao',
        'uses' => 'Painel\BlogComentariosController@aprovacao'
    ]);
    Route::resource('blog.comentarios', 'Painel\BlogComentariosController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato/creditos', 'Painel\CreditosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/models/Cenografia.php
<?php

class Cenografia extends Eloquent
{

    protected $table = 'cenografia';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function imagens()
    {
        return $this->hasMany('CenografiaImagem', 'cenografia_id')->orderBy('ordem', 'ASC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

}

laravel/app/controllers/CenografiaController.php
<?php

class CenografiaController extends BaseController {

    public function index($slug = null)
    {
        View::share('categoria', 'cenografia');
        View::share('projetos', Cenografia::ordenados()->get());

        if (!$slug) {

            return $this->view('frontend.projetos.index');

        } else {

            $selecionado = Cenografia::with('imagens')->slug($slug)->first();
            if (!$selecionado) App::abort('404');

            View::share('custom_layout', 'projeto');
            View::share('selecionado', $selecionado);
            return $this->view('frontend.projetos.show');

        }
    }

}

laravel/app/controllers/painel/CenografiaController.php
<?php

namespace Painel;

use \Cenografia, \Input, \Session, \Redirect, \Validator, \Str, \CropImage;

class CenografiaController extends BasePainelController {

    private $validation_rules = [
        'titulo' => 'required',
        'capa'   => 'required|image'
    ];

    private $image_config = [
        'width'  => 300,
        'height' => 300,
        'path'   => 'assets/img/cenografia/capa/'
    ];

    public function index()
    {
        $cenografia = Cenografia::ordenados()->get();

        return $this->view('painel.cenografia.index', compact('cenografia'));
    }

    public function create()
    {
        return $this->view('painel.cenografia.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['capa'] = CropImage::make('capa', $this->image_config);
            Cenografia::create($input);
            Session::flash('sucesso', 'Projeto criado com sucesso.');

            return Redirect::route('painel.cenografia.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar projeto. Verifique se já existe outro projeto com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $cenografia = Cenografia::findOrFail($id);

        return $this->view('painel.cenografia.edit', compact('cenografia'));
    }

    public function update($id)
    {
        $cenografia = Cenografia::findOrFail($id);
        $input   = Input::all();

        $this->validation_rules['capa'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            $cenografia->update($input);
            Session::flash('sucesso', 'Projeto alterado com sucesso.');

            return Redirect::route('painel.cenografia.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar projeto. Verifique se já existe outro projeto com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Cenografia::destroy($id);
            Session::flash('sucesso', 'Projeto removido com sucesso.');

            return Redirect::route('painel.cenografia.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover projeto.']);

        }
    }

}

laravel/app/views/painel/cenografia/imagens/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="well form-group">
    {{ Form::label('imagem', 'Imagem') }}
    {{ Form::file('imagem', ['class' => 'form-control']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.cenografia.imagens.index', $cenografia->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/cenografia/imagens/create.blade.php
@section('content')

    <legend>
        <h2><small>Cenografia / Adicionar Imagem ao Projeto:</small> {{ $cenografia->titulo }}</h2>
    </legend>

    {{ Form::open(['route' => ['painel.cenografia.imagens.store', $cenografia->id], 'files' => true]) }}

        @include('painel.cenografia.imagens._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/cenografia/imagens/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <a href="{{ route('painel.cenografia.index') }}" title="Voltar para Cenografia" class="btn btn-default">&larr; Voltar para Cenografia</a>

    <legend>
        <h2>
            <small>Cenografia / Imagens do Projeto:</small> {{ $cenografia->titulo }}
            <a href="{{ URL::route('painel.cenografia.imagens.create', $cenografia->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Imagem</a>
        </h2>
    </legend>

    @if(count($imagens))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="cenografia_imagens">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($imagens as $imagem)

                <tr class="tr-row" id="id_{{ $imagem->id }}">
                    <td>
                        <a href="#" class="btn btn-info btn-sm btn-move">
                            <span class="glyphicon glyphicon-move"></span>
                        </a>
                    </td>
                    <td><img src="{{ url('assets/img/cenografia/'.$imagem->imagem) }}" alt="" style="width:100%;max-width:200px;height:auto;"></td>
                    <td class="crud-actions">
                       {{ Form::open(array('route' => array('painel.cenografia.imagens.destroy', $cenografia->id, $imagem->id), 'method' => 'delete')) }}
                        <input type="hidden" name="cenografia_id" value="{{ $cenografia->id }}">
                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                       {{ Form::close() }}
                    </td>
                </tr>

            @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma imagem cadastrada.</div>
    @endif

</div>

@stop